# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Multims < Formula
  desc "How engineers learn about CLIs"
  homepage "https://github.com/JACKT72xp/cli"
  version "1.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JACKT72xp/multims/releases/download/v1.1.3/multims_1.1.3_darwin_amd64.tar.gz"
      sha256 "5a5b5b28ee7a93797618f196359210ee6a3094b0cd38f8c424fb7ba3d74a2e8a"

      def install
        bin.install "multims"
        (etc/"multims").mkpath
        (etc/"multims/templates").install Dir["templates/*"]
        (etc/"multims/scripts").install Dir["scripts/*"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JACKT72xp/multims/releases/download/v1.1.3/multims_1.1.3_darwin_arm64.tar.gz"
      sha256 "897a43c602da2629b15f8063b89c3a8ea68268fc960c86286ecb1b9cde374089"

      def install
        bin.install "multims"
        (etc/"multims").mkpath
        (etc/"multims/templates").install Dir["templates/*"]
        (etc/"multims/scripts").install Dir["scripts/*"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/JACKT72xp/multims/releases/download/v1.1.3/multims_1.1.3_linux_amd64.tar.gz"
      sha256 "e5a2ff18369b75cbd2e534008ce8c434a3ca7a74e313b7f6a47a84cdbdea95dd"

      def install
        bin.install "multims"
        (etc/"multims").mkpath
        (etc/"multims/templates").install Dir["templates/*"]
        (etc/"multims/scripts").install Dir["scripts/*"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JACKT72xp/multims/releases/download/v1.1.3/multims_1.1.3_linux_arm64.tar.gz"
      sha256 "c6d38d59ef686e4a9569ca21d28a3965fd87dd7f0a15317054e705b4ce51dcf4"

      def install
        bin.install "multims"
        (etc/"multims").mkpath
        (etc/"multims/templates").install Dir["templates/*"]
        (etc/"multims/scripts").install Dir["scripts/*"]
      end
    end
  end

  def caveats
    <<~EOS
      Templates are located in #{etc/"multims/templates"}.
      Scripts are located in #{etc/"multims/scripts"}.
      Make sure fswatch is installed by running `brew install fswatch`.
    EOS
  end
end
