# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Multims < Formula
  desc "How engineers learn about CLIs"
  homepage "https://github.com/JACKT72xp/cli"
  version "1.1.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JACKT72xp/multims/releases/download/v1.1.10/multims_1.1.10_darwin_amd64.tar.gz"
      sha256 "6ac1f83ede4d25a5510855790fdf8df88add7c099ead6da95eafc52d0268c172"

      def install
        bin.install "multims"
        (etc/"multims").mkpath
        (etc/"multims/templates").install Dir["templates/*"]
        (etc/"multims/scripts").install Dir["scripts/*"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JACKT72xp/multims/releases/download/v1.1.10/multims_1.1.10_darwin_arm64.tar.gz"
      sha256 "6b73c2474d2d0d398e750b3ed8cde164f97c5284901b9fc68cdca075fd55cb56"

      def install
        bin.install "multims"
        (etc/"multims").mkpath
        (etc/"multims/templates").install Dir["templates/*"]
        (etc/"multims/scripts").install Dir["scripts/*"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/JACKT72xp/multims/releases/download/v1.1.10/multims_1.1.10_linux_amd64.tar.gz"
      sha256 "244046a1163f8402d0296a74fc80cf8dd809dbe216e3d6de8e4c4db1c0cba28e"

      def install
        bin.install "multims"
        (etc/"multims").mkpath
        (etc/"multims/templates").install Dir["templates/*"]
        (etc/"multims/scripts").install Dir["scripts/*"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JACKT72xp/multims/releases/download/v1.1.10/multims_1.1.10_linux_arm64.tar.gz"
      sha256 "b1fdaf0dba1b51cb3dc07d65240cf6fddafe5afbf06cde5242e8d2aa9853e0db"

      def install
        bin.install "multims"
        (etc/"multims").mkpath
        (etc/"multims/templates").install Dir["templates/*"]
        (etc/"multims/scripts").install Dir["scripts/*"]
      end
    end
  end

  def caveats
    <<~EOS
      Templates are located in #{etc/"multims/templates"}.
      Scripts are located in #{etc/"multims/scripts"}.
      Make sure fswatch is installed by running `brew install fswatch`.
    EOS
  end
end
